name: cim-hamilton.org
favicon: null
layout_spectrum: 0.33944339607842267
typography_spectrum: 0.2225256748497486
title: CIM Hamilton
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d235d'
    - '#434b9c'
    - '#d4d9df'
    - '#92a5c5'
    - '#ab6c5a'
  brandStrength: 0.10954141081310809
  lightness: 0.8436345150694251
  saturation: 0.641701917629689
  rhythmicContrast: 0.9589643890503794
purpose: []
