typography_spectrum: 0.9994
color:
  brandColors:
    - '#1d235d'
    - '#434b9c'
    - '#d4d9df'
    - '#92a5c5'
    - '#ab6c5a'
  brandStrength: 0.10954141081310809
  lightness: 0.8436345150694251
  saturation: 0.641701917629689
  rhythmicContrast: 0.9589643890503794
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.99338
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Denise McMullin
  email: dmcmullincim@gmail.com
  url: cim-hamilton.org
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/0f570e5c-e35c-4504-9f7f-577e33f2777b.jpg
name: cim-hamilton.org
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Canadian Institute of Management Hamilton Chapter
description: Become a Certified Manager
purpose: []
